# Boot from disk, patch and rebuild the system

set cpu 11/93
set cpu 4m
set cpu idle

set tq enabled
attach -e tq0 -F TAR data.tar

set rq enabled
set rq0 ra81
attach -e rq0 rq0.dsk

# handle BSD errors by exiting with non-zero code
expect "EXEC_BSD_FAILED" exit 1

# login as root
expect "login:" send "root\r"; continue

# set hostname and timezone, they are included in the kernel
expect '\n#' do exec-bsd "hostname pdp11.local"; continue
expect '\n#' do exec-bsd "TZ=GMT; export TZ"; continue

# read files from the data tape
expect '\n#' do exec-bsd "cd /tmp"; continue
expect '\n#' do exec-bsd "mt rewind"; continue
expect '\r#' do exec-bsd "tar xvf /dev/rmt12"; continue

# apply patches
expect '\n#' do exec-bsd "cd /"; continue

# 482 is already partially applied, fix to make 482.patch apply cleanly
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/fix-482.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/482.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/483.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/484.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/485.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/486.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/487.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/488.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/489.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/490.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/491.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/492.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/493.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/494.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/495.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/496.patch"; continue
# 497 is not a patch, it's an archive to unpack by 497.sh
expect '\n#' do exec-bsd "mv /tmp/data/497.patch /tmp/497.patch"; continue
expect '\n#' do exec-bsd "patch -p0 < /tmp/data/498.patch"; continue

# rebuild the kernel
expect '\n#' do exec-bsd "cd /usr/src/sys/conf"; continue
expect '\n#' do exec-bsd "cp /tmp/data/SIMH ."; continue
expect '\n#' do exec-bsd "./config SIMH"; continue
expect '\n#' do exec-bsd "cd /sys/SIMH"; continue
expect '\n#' do exec-bsd "patch Makefile /tmp/data/Makefile.patch"; continue
expect '\n#' do exec-bsd "make"; continue
expect '\n#' do exec-bsd "cp /unix /oldunix"; continue
expect '\n#' do exec-bsd "make install"; continue

# rebuild the userspace
expect '\n# ' do exec-bsd "/tmp/data/482.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/483.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/484.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/485.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/486.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/487.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/488.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/489.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/490.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/491.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/492.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/493.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/494.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/495.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/496.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/497.sh"; continue
expect '\n# ' do exec-bsd "/tmp/data/498.sh"; continue

# clean up after applying patches
expect '\n# ' do exec-bsd "cd / ; find . -name '*~' -print | xargs rm -f"; continue

# shut down
expect '\n# ' do exec-bsd "sync"; continue
expect '\n# ' send after=100m,"shutdown -h now\r"; continue

boot rq0

exit
