# Boot from disk in single user mode, populate rest of the file system

set cpu 11/93
set cpu 4m
set cpu idle

set tq enabled
attach -e tq0 -F TAR data.tar

set rq enabled
set rq0 ra81
attach -e rq0 rq0.dsk

# handle BSD errors by exiting with non-zero code
expect "EXEC_BSD_FAILED" exit 1

# boot to single user mode
expect 'Press <CR> to boot, or any other key to abort' send " ra(0,0,0)unix -s\r"; continue

# initialize the /usr file system
expect '\n#' do exec-bsd "newfs ra0d"; continue

# read files from the data tape
expect '\n#' do exec-bsd "cd /tmp"; continue
expect '\n#' do exec-bsd "mt -f /dev/rmt12 rewind"; continue
expect '\r#' do exec-bsd "tar xvf /dev/rmt12"; continue

# install new /etc/fstab
expect '\n#' do exec-bsd "cp /tmp/data/fstab /etc/fstab"; continue

# mount all file systems
expect '\n#' do exec-bsd "mount -a"; continue
expect '\n#' do exec-bsd "df"; continue

# load the distribution tape
expect '\n#' do exec-bsd "mt offline"; continue
expect '\n#' attach -e tq0 2.11bsd.tap; send "\r"; continue

# populate /usr
expect '\n#' do exec-bsd "cd /usr"; continue
expect '\n#' do exec-bsd "mt -f /dev/rmt12 rewind"; continue
expect '\n#' do exec-bsd "mt -f /dev/rmt12 fsf 6"; continue
expect '\n#' do exec-bsd "echo 'this will take a few minutes'"; continue
expect '\n#' do exec-bsd "tar xpbf 20 /dev/rmt12"; continue

# populate /usr/src/sys and /usr/src/include
expect '\n#' do exec-bsd "mkdir /usr/src"; continue
expect '\n#' do exec-bsd "cd /usr/src"; continue
expect '\n#' do exec-bsd "mt -f /dev/rmt12 fsf"; continue
expect '\n#' do exec-bsd "echo 'this will take a few minutes'"; continue
expect '\n#' do exec-bsd "tar xpbf 20 /dev/rmt12"; continue

# populate rest pf /usr/src
expect '\n#' do exec-bsd "cd /usr/src"; continue
expect '\n#' do exec-bsd "mt -f /dev/rmt12 fsf"; continue
expect '\n#' do exec-bsd "echo 'this will take a few minutes'"; continue
expect '\n#' do exec-bsd "tar xpbf 20 /dev/rmt12"; continue

# additional setup
expect '\n#' do exec-bsd "cd /"; continue
expect '\n#' do exec-bsd "chmod 755 / /usr /usr/src /usr/src/sys"; continue
expect '\n#' do exec-bsd "rm -f sys"; continue
expect '\n#' do exec-bsd "ln -s /usr/src/sys sys"; continue

# patch /etc/rc to continue booting after fsck modifies the root file system
expect '\n#' do exec-bsd "patch /etc/rc /tmp/data/rc.patch"; continue

# shut down
expect '\n#' do exec-bsd "sync"; continue
expect '\n#' send after=100m,"shutdown -h now\r"; continue

boot rq0

exit
