version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/2.11bsd"
      - "/unix-v6"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
