*** Makefile.orig	Fri Oct  4 09:59:42 2024
--- Makefile	Fri Oct  4 10:00:43 2024
***************
*** 63,69 ****
  	rk.o rl.o rx.o si.o subr_rmap.o sys_inode.o sys_kern.o \
  	tm.o ts.o tty.o tty_conf.o tty_subr.o tty_tb.o ufs_alloc.o \
  	ufs_bio.o ufs_fio.o ufs_inode.o ufs_namei.o \
! 	vm_proc.o vm_sched.o vm_swap.o xp.o quota_subr.o
  OV1=	sys_generic.o ufs_syscalls.o vfs_vnops.o
  OV2=	kern_acct.o kern_exec.o kern_exit.o kern_fork.o kern_resource.o
  OV3=	kern_time.o sys_process.o ufs_mount.o ufs_subr.o uipc_syscalls.o
--- 63,70 ----
  	rk.o rl.o rx.o si.o subr_rmap.o sys_inode.o sys_kern.o \
  	tm.o ts.o tty.o tty_conf.o tty_subr.o tty_tb.o ufs_alloc.o \
  	ufs_bio.o ufs_fio.o ufs_inode.o ufs_namei.o \
! 	vm_proc.o vm_sched.o vm_swap.o xp.o quota_subr.o \
! 	ufs_disksubr.o ufs_dsort.o ufs_syscalls2.o kern_sig2.o
  OV1=	sys_generic.o ufs_syscalls.o vfs_vnops.o
  OV2=	kern_acct.o kern_exec.o kern_exit.o kern_fork.o kern_resource.o
  OV3=	kern_time.o sys_process.o ufs_mount.o ufs_subr.o uipc_syscalls.o
***************
*** 71,81 ****
  OV5=	quota_kern.o quota_ufs.o quota_sys.o ufs_bmap.o	\
  	sys_pipe.o
  # OV6 gets the (hopefully) never used routines
! OV6=	clock.o dn.o init_main.o kern_pdp.o machdep2.o subr_prf.o syscalls.o \
  	subr_log.o toy.o vm_swp.o
! OV7=	ufs_disksubr.o ufs_dsort.o ufs_syscalls2.o kern_sig2.o
! OV8=	mch_fpsim.o kern_sysctl.o kern_xxx.o ingreslock.o vm_text.o
! OV9=	tmscp.o tmscpdump.o
  
  KERNOBJ=${CONF} ${BASE} ${OV1} ${OV2} ${OV3} ${OV4} ${OV5} \
  	${OV6} ${OV7} ${OV8} ${OV9} ${OV10} ${OV11} ${OV12} \
--- 72,82 ----
  OV5=	quota_kern.o quota_ufs.o quota_sys.o ufs_bmap.o	\
  	sys_pipe.o
  # OV6 gets the (hopefully) never used routines
! OV6=	clock.o dn.o kern_pdp.o machdep2.o subr_prf.o syscalls.o \
  	subr_log.o toy.o vm_swp.o
! OV7=	mch_fpsim.o kern_sysctl.o kern_xxx.o ingreslock.o vm_text.o \
! 	init_main.o
! OV8=	tmscp.o tmscpdump.o
  
  KERNOBJ=${CONF} ${BASE} ${OV1} ${OV2} ${OV3} ${OV4} ${OV5} \
  	${OV6} ${OV7} ${OV8} ${OV9} ${OV10} ${OV11} ${OV12} \
